services:
  djangodb:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=unboxr
      - POSTGRES_USER=unboxr
      - POSTGRES_PASSWORD=unboxr

  # djangoDev:
  #   build:
  #     context: ./backend
  #     dockerfile: docker/DjangoDockerfile
  #   image: xlharambe/unboxr-backend:latest
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - POSTGRES_NAME=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_HOST=postgres
  #     - SCRAPYD_SERVERS=scrapyd:6080
  #     - SECRET_KEY=TEST
  #     - DEPLOYMENT_ENVIRONMENT=prod
  #   depends_on:
  #     - djangodb

  djangoProd:
    build:
      context: ./backend
      dockerfile: docker/DjangoProductionDockerfile
    image: xlharambe/unboxr-backend:latest
    volumes:
      - .app:/usr/src/django
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=unboxr
      - POSTGRES_USER=unboxr
      - POSTGRES_PASSWORD=unboxr
      - POSTGRES_HOST=djangodb
      - SECRET_KEY=TEST
      - DEPLOYMENT_ENVIRONMENT=prod
      - DEBUG=True
      - MONGO_HOSTNAME=scrapyDatabase
      - MONGO_PORT=27017
      - MONGO_DBNAME=unboxr
      - MONGO_COLLECTION=products-crawler
      - MONGO_USER=root
      - MONGO_PASS=example
      - SCRAPYD_PROJECT=default
      - SCRAPYD_PORT=6800
      - SCRAPYD_USERNAME=scrapy
      - SCRAPYD_PASSWORD=secret
      - SCRAPYD_HOST_NAME=scrapyd
    depends_on:
      - djangodb

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

  celery:
    build:
      context: ./backend
      dockerfile: docker/CeleryDockerfile
    command: celery -A backend worker --loglevel=debug
    # command: tail -f /dev/null
    volumes:
      - .app:/usr/src/django
    environment:
      - DEPLOYMENT_ENVIRONMENT=prod
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - POSTGRES_NAME=unboxr
      - POSTGRES_USER=unboxr
      - POSTGRES_PASSWORD=unboxr
      - POSTGRES_HOST=djangodb
      - SECRET_KEY=TEST
      - DEBUG=True
      - MONGO_HOSTNAME=scrapyDatabase
      - MONGO_PORT=27017
      - MONGO_DBNAME=unboxr
      - MONGO_COLLECTION=products-crawler
      - MONGO_USER=root
      - MONGO_PASS=example
      - SCRAPYD_PROJECT=default
      - SCRAPYD_PORT=6800
      - SCRAPYD_USERNAME=scrapy
      - SCRAPYD_PASSWORD=secret
      - SCRAPYD_HOST_NAME=scrapyd
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
      - celery-beat

  celery-beat:
    build:
      context: ./backend
      dockerfile: docker/CeleryDockerfile
    command: celery -A backend beat --loglevel=debug --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .app:/usr/src/django
    environment:
      - DEPLOYMENT_ENVIRONMENT=dev
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    #   # - DEBUG=1
    #   # - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
    #   # - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis

  celer-flower:
    build:
      context: ./backend
      dockerfile: docker/CeleryDockerfile
    command: celery -A backend flower --port=5566
    volumes:
      - .app:/usr/src/django
    environment:
      - DEPLOYMENT_ENVIRONMENT=dev
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    #   # - DEBUG=1
    #   # - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
    #   # - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    ports:
      - 5566:5566
    depends_on:
      - celery

  scrapyDatabase:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: unboxr
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017

  scrapyd:
    build:
      context: ./scraper
      dockerfile: docker/ScrapydDockerFile
    image: xlharambe/unboxr-scrapyd-backend:latest
    environment:
      MONGO_HOSTNAME: scrapyDatabase
      MONGO_PORT: 27017
      MONGO_DBNAME: unboxr
      MONGO_COLLECTION: products-crawler
      MONGO_USER: root
      MONGO_PASS: example
    ports:
      - 6800:6800
    restart: unless-stopped
    depends_on:
      - scrapyDatabase

  scrapydweb:
    build:
      context: ./scraper
      dockerfile: docker/ScrapydwebDockerFile
    image: xlharambe/unboxr-scrapyd-ui:latest
    environment:
      SCRAPYD_SERVERS: "scrapy:secret@scrapyd:6800#default"
      TARGET: http://scrapyd:6800
      PROJECT: products
    ports:
      - 5000:5000
    restart: unless-stopped
    depends_on:
      - scrapyd

volumes:
  .app:
  mongodb:
  static_volume:
  media_volume:
  postgres_data:
  redis-data:
  redis-conf:
