# this file is for creating blueprints on render.com
databases:
  - name: unboxrAPI
    databaseName: unboxr
    user: admin

services:
  - type: web
    name: unboxrAPI
    env: python
    buildCommand: "./backend/build.sh"
    startCommand: "gunicorn unboxrAPI.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: unboxrAPI
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4