# this file is for creating blueprints on render.com
databases:
  - name: unboxrAPI
    databaseName: unboxr
    user: admin
    plan: free

services:
  - type: web
    name: unboxrAPI
    env: python
    buildCommand: "./backend/build.sh"
    startCommand: "gunicorn backend.wsgi:application"
#     plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: unboxrAPI
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.8.3
      - key: DEPLOYMENT_ENVIRONMENT
        value: prod
