# this file is for creating blueprints on render.com
databases:
  - name: unboxr-API
    databaseName: unboxr
    user: unboxr-admin

services:
  - type: web
    name: unboxr-API
    env: python
    buildCommand: "./backend/build.sh"
    startCommand: "gunicorn unboxr-API.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: unboxr-API
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4