# Generated by Django 4.1.4 on 2022-12-26 17:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='n/a', max_length=255)),
                ('company_website', models.URLField(default='n/a')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField(blank=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_page', models.URLField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductIdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_type', models.CharField(choices=[('Tik', 'Tik Tok'), ('Insta', 'Instagram'), ('Fb', 'Facebook'), ('Yt', 'Youtube')], default='na', max_length=255)),
                ('coupon_code', models.CharField(blank=True, max_length=255, null=True)),
                ('coupon_description', models.TextField(blank=True, null=True)),
                ('post_link', models.URLField()),
                ('post_promotion_date', models.DateTimeField(default=datetime.datetime(2022, 12, 26, 12, 35, 18, 369690))),
                ('promotion_expiration_date', models.DateTimeField(blank=True, null=True)),
                ('advertisement_link', models.URLField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unboxr.influencer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unboxr.product')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('unboxing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='unboxr.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSkuId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id_value', models.CharField(max_length=255)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ids', to='unboxr.product')),
                ('product_id_type', models.ManyToManyField(related_name='product_id_type', to='unboxr.productidtype')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='unboxr.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_categories',
            field=models.ManyToManyField(related_name='products', to='unboxr.product_category'),
        ),
        migrations.CreateModel(
            name='InfluencerSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_type', models.CharField(choices=[('Tik', 'Tik Tok'), ('Insta', 'Instagram'), ('Fb', 'Facebook'), ('Yt', 'Youtube')], default='na', max_length=255)),
                ('social_media_username', models.CharField(max_length=255)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='unboxr.influencer')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Promotion_images')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('unboxing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='unboxr.promotion')),
            ],
        ),
    ]
