# Generated by Django 4.1.4 on 2022-12-22 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unboxr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='post_promotion_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 14, 13, 37, 748774)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 14, 13, 37, 748774)),
        ),
    ]
