# Generated by Django 4.1.4 on 2022-12-30 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unboxr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_page',
        ),
        migrations.AddField(
            model_name='product',
            name='merchant_product_page',
            field=models.URLField(default='', help_text='Link to the product page on merchant websites.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='company_website',
            field=models.URLField(default='n/a', help_text='Website to the source company that manufactures the product.'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='post_promotion_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 11, 41, 59, 485352)),
        ),
    ]
