# Generated by Django 4.1.4 on 2022-12-30 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unboxr', '0002_remove_product_product_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='post_promotion_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 12, 29, 24, 828268)),
        ),
    ]
