# Generated by Django 4.1.4 on 2022-12-22 19:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unboxr', '0002_alter_promotion_post_promotion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unboxr.product'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='post_promotion_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 14, 14, 8, 619712)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 14, 14, 8, 619712)),
        ),
    ]
