# Generated by Django 4.1.4 on 2022-12-22 19:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unboxr', '0003_promotion_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_other_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_sku',
        ),
        migrations.AlterField(
            model_name='influencer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='advertisement_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='coupon_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='post_promotion_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 14, 49, 12, 391565)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductSkuId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id_value', models.CharField(max_length=255)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unboxr.product')),
                ('product_id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unboxr.productidtype')),
            ],
        ),
    ]
