# Generated by Django 4.1.4 on 2022-12-30 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unboxr', '0003_alter_promotion_post_promotion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='coupon_code_in_the_link',
            field=models.URLField(blank=True, help_text='This field will be populated if the coupon code is directly in the link', null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='post_promotion_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 13, 4, 48, 561382)),
        ),
    ]
