# Generated by Django 4.1.4 on 2022-12-22 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unboxr', '0004_productidtype_remove_product_product_other_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productskuid',
            name='product_id_type',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='post_promotion_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 14, 52, 44, 9296)),
        ),
        migrations.AddField(
            model_name='productskuid',
            name='product_id_type',
            field=models.ManyToManyField(related_name='product_id_type', to='unboxr.productidtype'),
        ),
    ]
