# Generated by Django 4.1.4 on 2022-12-30 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unboxr', '0005_rename_unboxing_image_promotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='post_promotion_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 13, 34, 54, 848315)),
        ),
    ]
