# Generated by Django 4.1.4 on 2022-12-24 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unboxr', '0005_remove_productskuid_product_id_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productidtype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='post_promotion_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 19, 44, 34, 635536)),
        ),
    ]
