# Generated by Django 4.1.4 on 2022-12-30 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unboxr', '0006_alter_promotion_post_promotion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='post_promotion_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 13, 36, 13, 221955)),
        ),
    ]
