# Generated by Django 4.1.4 on 2023-01-19 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unboxr', '0008_alter_promotion_post_promotion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='post_promotion_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 17, 55, 23, 517530)),
        ),
    ]
