version: "3.3"

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: unboxr
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017

  # scrapy:
  #   build:
  #     dockerfile: docker/ProductsScrapyDockerFile
  #   environment:
  #     MONGO_HOSTNAME: mongodb
  #     MONGO_PORT: 27017
  #     MONGO_DBNAME: unboxr
  #     MONGO_COLLECTION: products-crawler
  #     MONGO_USER: root
  #     MONGO_PASS: example
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - mongodb

  scrapyd:
    build:
      dockerfile: docker/ScrapydDockerFile
    environment:
      MONGO_HOSTNAME: mongodb
      MONGO_PORT: 27017
      MONGO_DBNAME: unboxr
      MONGO_COLLECTION: products-crawler
      MONGO_USER: root
      MONGO_PASS: example
    ports:
      - 6800:6800
    restart: unless-stopped
    depends_on:
      - mongodb

  # scrapyd:
  #   image: easypi/scrapyd
  #   environment:
  #     MONGO_HOSTNAME: mongodb
  #     MONGO_PORT: 27017
  #     MONGO_DBNAME: unboxr
  #     MONGO_COLLECTION: products-crawler
  #     MONGO_USER: root
  #     MONGO_PASS: example
  #   ports:
  #     - "6800:6800"
  #   volumes:
  #     - ./data:/var/lib/scrapyd
  #     - /usr/local/lib/python3.9/dist-packages
  #   restart: unless-stopped
  #   depends_on:
  #     - mongodb

  scrapydweb:
    build:
      dockerfile: docker/ScrapydwebDockerFile
    environment:
      SCRAPYD_SERVERS: "scrapy:secret@scrapyd:6800#default"
      TARGET: http://scrapyd:6800
      PROJECT: products
    ports:
      - 5000:5000
    volumes:
      - .:/app
    # volumes:
    #   - ./data:/var/lib/scrapyd
    #   - /usr/local/lib/python3.9/dist-packages
    # restart: unless-stopped
    depends_on:
      - scrapyd
  # scrapyrt:
  #   image: easypi/scrapyd
  #   command: scrapyrt -i 0.0.0.0 -p 9080
  #   ports:
  #     - "9080:9080"
  #   volumes:
  #     - .:/code
  #   working_dir: /code
  #   restart: unless-stopped

volumes:
  mongodb:

    # networks:
    #   default:
    #     external: true
