version: "3.8"

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: unboxr
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017

  scrapy:
    build:
      context: .
      dockerfile: DockerFile
    environment:
      MONGO_HOSTNAME: mongodb
      MONGO_PORT: 27017
      MONGO_DBNAME: unboxr
      MONGO_COLLECTION: products-crawler
      MONGO_USER: root
      MONGO_PASS: example
    volumes:
      - .:/app
    depends_on:
      - mongodb

volumes:
  mongodb:
