version: "3.3"

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: unboxr
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017

  crawlab_master:
    image: crawlabteam/crawlab
    container_name: crawlab_master
    restart: always
    environment:
      CRAWLAB_NODE_MASTER: Y
      CRAWLAB_MONGO_HOST: localhost
      CRAWLAB_MONGO_PORT: 27017
      CRAWLAB_MONGO_DB: unboxr
      CRAWLAB_MONGO_USERNAME: root
      CRAWLAB_MONGO_PASSWORD: example
    volumes:
      - /opt/crawlab/master:/data # persistent crawlab data
    ports:
      - 8080:8080 # exposed api port
    depends_on:
      - mongodb
  # scrapy:
  #   build:
  #     context: .
  #     dockerfile: DockerFile
  #   environment:
  #     MONGO_HOSTNAME: mongodb
  #     MONGO_PORT: 27017
  #     MONGO_DBNAME: unboxr
  #     MONGO_COLLECTION: products-crawler
  #     MONGO_USER: root
  #     MONGO_PASS: example
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - mongodb

volumes:
  mongodb:
