version: "3.3"

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: unboxr
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017

  crawlab_master:
    image: crawlabteam/crawlab
    container_name: crawlab_master
    restart: always
    environment:
      CRAWLAB_NODE_MASTER: "Y" # Y: master node
      CRAWLAB_MONGO_HOST: "localhost" # mongo host address. In the docker compose network, directly refer to the service name
      CRAWLAB_MONGO_PORT: "27017" # mongo port 
      CRAWLAB_MONGO_DB: "unboxr" # mongo database 
      CRAWLAB_MONGO_USERNAME: "root" # mongo username
      CRAWLAB_MONGO_PASSWORD: "example" # mongo password 
      CRAWLAB_MONGO_AUTHSOURCE: "admin" # mongo auth source 
    volumes:
      - "/opt/crawlab/master:/data" # persistent crawlab data
    ports:
      - "8080:8080" # exposed api port
    depends_on:
      - mongodb

  scrapy:
    build:
      context: .
      dockerfile: DockerFile
    environment:
      MONGO_HOSTNAME: mongodb
      MONGO_PORT: 27017
      MONGO_DBNAME: unboxr
      MONGO_COLLECTION: products-crawler
      MONGO_USER: root
      MONGO_PASS: example
    volumes:
      - .:/app
    depends_on:
      - mongodb

volumes:
  mongodb:
